corregido carpeta, ahora si

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,31 +26,30 @@ jobs:
   deploy:
     needs: build
     runs-on: ubuntu-latest
-    environment: dev
+    environment: dev   # <-- Aquí asignas el environment 'dev'
     steps:
-      
+      - name: Checkout code
+        uses: actions/checkout@v3
 
-      - name: Comprobar secretos
+      - name: Verificar secretos
         run: |
           if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
             echo "ERROR: HEROKU_API_KEY está vacío"
             exit 1
-          else
-            echo "HEROKU_API_KEY está configurado"
           fi
-
-
-      
-      - name: Checkout code
-        uses: actions/checkout@v3
+          if [ -z "${{ secrets.HEROKU_APP_NAME }}" ]; then
+            echo "ERROR: HEROKU_APP_NAME está vacío"
+            exit 1
+          fi
+          if [ -z "${{ secrets.HEROKU_EMAIL }}" ]; then
+            echo "ERROR: HEROKU_EMAIL está vacío"
+            exit 1
+          fi
+          echo "Todos los secretos están definidos"
 
       - name: Deploy to Heroku
         uses: akhileshns/heroku-deploy@v3.12.12
         with:
           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
-          heroku_app_name: "evaluaciondan"
-          heroku_email: "danielitasr03@gmail.com"
-
-
-
-
+          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
+          heroku_email: ${{ secrets.HEROKU_EMAIL }}
